# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2048, 1200)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = Label(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayout.setStretch(1, 12)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2048, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionInitialize = QtWidgets.QAction(MainWindow)
        self.actionInitialize.setObjectName("actionInitialize")
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionDirectory = QtWidgets.QAction(MainWindow)
        self.actionDirectory.setObjectName("actionDirectory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPredict = QtWidgets.QAction(MainWindow)
        self.actionPredict.setObjectName("actionPredict")
        self.actionTrain = QtWidgets.QAction(MainWindow)
        self.actionTrain.setObjectName("actionTrain")
        self.actionDraw = QtWidgets.QAction(MainWindow)
        self.actionDraw.setObjectName("actionDraw")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setObjectName("actionLine")
        self.actionModel = QtWidgets.QAction(MainWindow)
        self.actionModel.setObjectName("actionModel")
        self.menuOpen.addAction(self.actionFile)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuRun.addAction(self.actionModel)
        self.menuRun.addAction(self.actionInitialize)
        self.menuRun.addAction(self.actionPredict)
        self.menuRun.addAction(self.actionTrain)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionStop)
        self.menuTool.addAction(self.actionLine)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())

        self.retranslateUi(MainWindow)
        self.actionPredict.triggered.connect(MainWindow.predict) # type: ignore
        self.actionInitialize.triggered.connect(MainWindow.initialize) # type: ignore
        self.actionTrain.triggered.connect(MainWindow.train) # type: ignore
        self.actionFile.triggered.connect(MainWindow.open_file) # type: ignore
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        self.actionSave.triggered.connect(MainWindow.save_file) # type: ignore
        self.actionStop.triggered.connect(MainWindow.stop) # type: ignore
        self.actionLine.triggered.connect(MainWindow.draw_line) # type: ignore
        self.actionModel.triggered.connect(MainWindow.select_model) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Statictics of Traffic Flow"))
        self.label_4.setText(_translate("MainWindow", "Ready to load file!"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionInitialize.setText(_translate("MainWindow", "Initialize"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionDirectory.setText(_translate("MainWindow", "Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionPredict.setText(_translate("MainWindow", "Predict"))
        self.actionTrain.setText(_translate("MainWindow", "Train"))
        self.actionDraw.setText(_translate("MainWindow", "draw"))
        self.actionReset.setText(_translate("MainWindow", "reset"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionLine.setText(_translate("MainWindow", "Line"))
        self.actionModel.setText(_translate("MainWindow", "Model"))
from .label import Label
